version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "reward-monitor-prod-stack"
s3_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1qnyfs2nvlwwf"
region = "us-east-1"
profile = "saddle-prod"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "reward-monitor-dev-stack"
s3_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-ruktl65kntz8"
region = "us-east-1"
profile = "saddle-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []