AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  reward-monitor-app

  For running simple job every 24 hours and trigger alerting if needed

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  AlchemyApiKey:
    Type: String
    Description: API key for Alchemy JSON RPC access
  EtherscanApi:
    Type: String
    Description: Etherscan API key for mainnet

Resources:
  RewardMonitorTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Timestamp
        Type: Number
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  RewardMonitorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 10
      CodeUri: reward-monitor-lambda-app/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref RewardMonitorTable
      Environment:
        Variables:
          TABLE_NAME: !Ref RewardMonitorTable
          ALCHEMY_API_KEY: !Ref AlchemyApiKey
          ETHERSCAN_API: !Ref EtherscanApi
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 ? * * *)
        GetRecentlySavedJson:
          Type: Api
          Properties:
            RestApiId: !Ref RewardMonitorApi
            Path: /check
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk"
          - "esbuild"

  RewardMonitorApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      CacheClusterEnabled: true
      CacheClusterSize: "0.5"
      MethodSettings:
        - CachingEnabled: true
          CacheTtlInSeconds: 3600 # 3600 secs max cache
          HttpMethod: "*" # Required for caching
          ResourcePath: "/*" # Requried for caching

Outputs:
  # Outputs can be checked under the CloudFormation stack page
  RewardMonitorFunction:
    Description: "Reward Monitor Lambda Function ARN"
    Value: !GetAtt RewardMonitorFunction.Arn
  RewardMonitorFunctionIamRole:
    Description: "Implicit IAM Role created for Reward Monitor Lambda function"
    Value: !GetAtt RewardMonitorFunctionRole.Arn
  ProdDataEndpoint:
    Description: "API Prod stage endpoint"
    Value: !Sub "https://${RewardMonitorApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"