name: StageProdDeploy

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          config-env: prod
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          sam-bucket: ${{ secrets.SAM_BUCKET }}
          pipeline-role: ${{ secrets.PIPELINE_ROLE }}
          deploy-role: ${{ secrets.DEPLOY_ROLE }}