name: Validate yml on Pull Requests

on:
  - pull_request

jobs:
  validate:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate
        with:
          config-env: prod
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          pipeline-role: ${{ secrets.PIPELINE_ROLE }}